### ISSUE TITLE
感谢闲心开源，正在使用中，发现提交表单时会触发个错误

### ISSUE THREAD

**Issue by ycrao** [layui/fly#1]
如题如图，不知道是何种原因造成的
![image](https://cloud.githubusercontent.com/assets/3280204/19798621/cc6fdfe4-9d24-11e6-8d31-3051e1962e16.png)
![image](https://cloud.githubusercontent.com/assets/3280204/19798642/e6275548-9d24-11e6-9cf2-2b2943661dd3.png)

**Comment by sentsin** [comment]
是哪个页面报的错？

**Comment by ycrao** [comment]
@sentsin 只要是表单（如注册表单），过了页面js form校验，往服务器上post提交写入时会发生js错误，页面上无任何回应，查看数据库是成功写入的。错误对应的源码行：https://github.com/layui/fly/blob/master/res/mods/index.js#L317
